<?php

return [
    'routes' => [
        'admin.dashboard' => ['dashboard', 'view'],
        'admin.home' => ['dashboard', 'view'],

        'dishes.index' => ['dishes', 'view'],
        'dishes.create' => ['dishes', 'create'],
        'dishes.store' => ['dishes', 'create'],
        'dishes.edit' => ['dishes', 'edit'],
        'dishes.update' => ['dishes', 'edit'],
        'dishes.destroy' => ['dishes', 'delete'],

        'customer.index' => ['customers', 'view'],
        'customer.create' => ['customers', 'create'],
        'customer.store' => ['customers', 'create'],
        'customer.edit' => ['customers', 'edit'],
        'customer.update' => ['customers', 'edit'],
        'customer.delete' => ['customers', 'delete'],

        'staff.index' => ['staff', 'view'],
        'staff.create' => ['staff', 'create'],
        'staff.store' => ['staff', 'create'],
        'staff.edit' => ['staff', 'edit'],
        'staff.update' => ['staff', 'edit'],
        'staff.destroy' => ['staff', 'delete'],

        'inventory.index' => ['inventory', 'view'],
        'inventory.create' => ['inventory', 'create'],
        'inventory.store' => ['inventory', 'create'],
        'inventory.edit' => ['inventory', 'edit'],
        'inventory.update' => ['inventory', 'edit'],
        'inventory.destroy' => ['inventory', 'delete'],
        'inventory.food' => ['inventory', 'view'],
        'inventory.decoration' => ['inventory', 'view'],
        'inventory.furniture' => ['inventory', 'view'],
        'inventory.crockery' => ['inventory', 'view'],
        'inventory.electronics' => ['inventory', 'view'],
        'inventory.stock' => ['inventory', 'view'],
        'inventory.stock.history' => ['inventory', 'view'],
        'inventory.stock.update' => ['inventory', 'edit'],
        'inventory.stock.reset_all' => ['inventory', 'delete'],
        'inventory.stock.restore' => ['inventory', 'edit'],

        'admin.booking.index' => ['booking', 'view'],
        'admin.booking.show' => ['booking', 'view'],
        'admin.booking.getCustomer' => ['booking', 'view'],
        'admin.booking.getPackageDishes' => ['booking', 'view'],
        'admin.booking.invoice' => ['booking', 'view'],
        'admin.booking.details.print' => ['booking', 'view'],
        'admin.booking.addPaymentPage' => ['booking', 'view'],
        'admin.booking.create' => ['booking', 'create'],
        'admin.booking.createWithCustomer' => ['booking', 'create'],
        'admin.booking.store' => ['booking', 'create'],
        'admin.booking.edit' => ['booking', 'edit'],
        'admin.booking.update' => ['booking', 'edit'],
        'admin.booking.addPayment' => ['booking', 'edit'],
        'admin.booking.extraGuest' => ['booking', 'edit'],
        'admin.booking.delete' => ['booking', 'delete'],

        'calendar.events' => ['booking', 'view'],

        'attendence.index' => ['attendance', 'view'],
        'attendence.view' => ['attendance', 'view'],
        'attendence.store' => ['attendance', 'edit'],
        'attendence.update' => ['attendance', 'edit'],
        'attendence.delete' => ['attendance', 'delete'],
        'attendence.updateStatus' => ['attendance', 'edit'],

        'admin.salary.index' => ['salary', 'view'],
        'admin.salary.show' => ['salary', 'view'],
        'admin.salary.getAbsentDays' => ['salary', 'view'],
        'admin.salary.create' => ['salary', 'create'],
        'admin.salary.store' => ['salary', 'create'],
        'admin.salary.delete' => ['salary', 'delete'],

        'admin.dish_package.index' => ['dish_packages', 'view'],
        'admin.dish_package.create' => ['dish_packages', 'create'],
        'admin.dish_package.store' => ['dish_packages', 'create'],
        'admin.dish_package.edit' => ['dish_packages', 'edit'],
        'admin.dish_package.update' => ['dish_packages', 'edit'],
        'admin.dish_package.destroy' => ['dish_packages', 'delete'],

        'admin.analysis.booking' => ['analysis', 'view'],
        'admin.analysis.inventory' => ['analysis', 'view'],
    ],
];
